// Code generated by runtime/_mkmalloc; DO NOT EDIT.
package gc

// AllocationAlignment returns the generated guarantee for the user pointer.
// ptrSize selects the target architecture, including cross-compilation.
// The sbrk debug allocator also obeys this guarantee.
func AllocationAlignment(size uint64, noscan bool, ptrSize uint64) uint64 {
	column := 0
	if ptrSize == 8 {
		column = 2
	}
	if noscan {
		column++
	}
	lo, hi := 0, len(allocationAlignments)-1
	for lo < hi {
		mid := (lo + hi) / 2
		if size <= allocationAlignments[mid].maxSize {
			hi = mid
		} else {
			lo = mid + 1
		}
	}
	return uint64(allocationAlignments[lo].alignment[column])
}

// Rows are inclusive size ranges. Columns are scan32, noscan32, scan64, noscan64.
// The final row covers all remaining sizes, including large allocations.
var allocationAlignments = [...]struct {
	maxSize   uint64
	alignment [4]uint16
}{
	{0, [4]uint16{4, 4, 8, 8}},
	{1, [4]uint16{8, 1, 8, 1}},
	{2, [4]uint16{8, 2, 8, 2}},
	{3, [4]uint16{8, 1, 8, 1}},
	{4, [4]uint16{8, 4, 8, 4}},
	{5, [4]uint16{8, 1, 8, 1}},
	{6, [4]uint16{8, 2, 8, 2}},
	{7, [4]uint16{8, 1, 8, 1}},
	{8, [4]uint16{8, 8, 8, 8}},
	{9, [4]uint16{16, 1, 16, 1}},
	{10, [4]uint16{16, 2, 16, 2}},
	{11, [4]uint16{16, 1, 16, 1}},
	{12, [4]uint16{16, 4, 16, 4}},
	{13, [4]uint16{16, 1, 16, 1}},
	{14, [4]uint16{16, 2, 16, 2}},
	{15, [4]uint16{16, 1, 16, 1}},
	{16, [4]uint16{16, 16, 16, 16}},
	{24, [4]uint16{8, 8, 8, 8}},
	{32, [4]uint16{32, 32, 32, 32}},
	{48, [4]uint16{16, 16, 16, 16}},
	{64, [4]uint16{64, 64, 64, 64}},
	{80, [4]uint16{16, 16, 16, 16}},
	{96, [4]uint16{32, 32, 32, 32}},
	{112, [4]uint16{16, 16, 16, 16}},
	{128, [4]uint16{128, 128, 128, 128}},
	{144, [4]uint16{8, 16, 16, 16}},
	{160, [4]uint16{8, 32, 32, 32}},
	{176, [4]uint16{8, 16, 16, 16}},
	{192, [4]uint16{8, 64, 64, 64}},
	{208, [4]uint16{8, 16, 16, 16}},
	{224, [4]uint16{8, 32, 32, 32}},
	{240, [4]uint16{8, 16, 16, 16}},
	{256, [4]uint16{8, 256, 256, 256}},
	{288, [4]uint16{8, 32, 32, 32}},
	{320, [4]uint16{8, 64, 64, 64}},
	{352, [4]uint16{8, 32, 32, 32}},
	{384, [4]uint16{8, 128, 128, 128}},
	{416, [4]uint16{8, 32, 32, 32}},
	{448, [4]uint16{8, 64, 64, 64}},
	{480, [4]uint16{8, 32, 32, 32}},
	{512, [4]uint16{8, 512, 512, 512}},
	{576, [4]uint16{8, 64, 8, 64}},
	{640, [4]uint16{8, 128, 8, 128}},
	{704, [4]uint16{8, 64, 8, 64}},
	{768, [4]uint16{8, 256, 8, 256}},
	{896, [4]uint16{8, 128, 8, 128}},
	{1024, [4]uint16{8, 1024, 8, 1024}},
	{1152, [4]uint16{8, 128, 8, 128}},
	{1280, [4]uint16{8, 256, 8, 256}},
	{1408, [4]uint16{8, 128, 8, 128}},
	{1536, [4]uint16{8, 512, 8, 512}},
	{1792, [4]uint16{8, 256, 8, 256}},
	{2048, [4]uint16{8, 2048, 8, 2048}},
	{2304, [4]uint16{8, 256, 8, 256}},
	{2688, [4]uint16{8, 128, 8, 128}},
	{3072, [4]uint16{8, 1024, 8, 1024}},
	{3456, [4]uint16{8, 128, 8, 128}},
	{4096, [4]uint16{8, 4096, 8, 4096}},
	{5376, [4]uint16{8, 256, 8, 256}},
	{6144, [4]uint16{8, 2048, 8, 2048}},
	{6784, [4]uint16{8, 128, 8, 128}},
	{6912, [4]uint16{8, 256, 8, 256}},
	{8192, [4]uint16{8, 8192, 8, 8192}},
	{9472, [4]uint16{8, 256, 8, 256}},
	{9728, [4]uint16{8, 512, 8, 512}},
	{10240, [4]uint16{8, 2048, 8, 2048}},
	{10880, [4]uint16{8, 128, 8, 128}},
	{12288, [4]uint16{8, 4096, 8, 4096}},
	{13568, [4]uint16{8, 256, 8, 256}},
	{14336, [4]uint16{8, 2048, 8, 2048}},
	{16384, [4]uint16{8, 8192, 8, 8192}},
	{18432, [4]uint16{8, 2048, 8, 2048}},
	{19072, [4]uint16{8, 128, 8, 128}},
	{20480, [4]uint16{8, 4096, 8, 4096}},
	{21760, [4]uint16{8, 256, 8, 256}},
	{24576, [4]uint16{8, 8192, 8, 8192}},
	{27264, [4]uint16{8, 128, 8, 128}},
	{28672, [4]uint16{8, 4096, 8, 4096}},
	{32760, [4]uint16{8, 8192, 8, 8192}},
	{^uint64(0), [4]uint16{8192, 8192, 8192, 8192}},
}
