// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
)

// allocationAlignment models the returned address, not merely the slot base.
// All allocation-path reasoning belongs in the generator; consumers only look up
// its result. Include race-mode tiny tail placement in the common guarantee.
func allocationAlignment(classes []class, size, ptrSize int, noscan bool) int {
	if size == 0 {
		return ptrSize
	}
	if noscan && size < tinySize {
		return min(size&-size, minHeapAlign)
	}
	if size > maxSmallSize-mallocHeaderSize {
		return pageSize
	}
	// The runtime keeps pointer bits in the span up to ptrSize * ptrBits.
	if !noscan && size > ptrSize*(ptrSize*8) {
		return mallocHeaderSize
	}
	for _, c := range classes {
		if c.size >= size {
			return min(c.size&-c.size, pageSize)
		}
	}
	panic("allocation size has no class")
}

func generateAllocationAlignments(classes []class) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by runtime/_mkmalloc; DO NOT EDIT.")
	fmt.Fprintln(&b, "package gc")
	fmt.Fprintln(&b, `
// AllocationAlignment returns the generated guarantee for the user pointer.
// ptrSize selects the target architecture, including cross-compilation.
// The sbrk debug allocator also obeys this guarantee.
func AllocationAlignment(size uint64, noscan bool, ptrSize uint64) uint64 {
 column := 0
 if ptrSize == 8 { column = 2 }
 if noscan { column++ }
 lo, hi := 0, len(allocationAlignments)-1
 for lo < hi {
  mid := (lo+hi)/2
  if size <= allocationAlignments[mid].maxSize { hi = mid } else { lo = mid+1 }
 }
 return uint64(allocationAlignments[lo].alignment[column])
}

// Rows are inclusive size ranges. Columns are scan32, noscan32, scan64, noscan64.
// The final row covers all remaining sizes, including large allocations.
var allocationAlignments = [...]struct {
 maxSize uint64
 alignment [4]uint16
}{`)
	var previous [4]int
	for size := 0; size <= maxSmallSize; size++ {
		var alignment [4]int
		for column := range alignment {
			alignment[column] = allocationAlignment(classes, size, 4+4*(column/2), column%2 != 0)
		}
		if size != 0 && alignment != previous {
			fmt.Fprintf(&b, "{%d, [4]uint16{%d, %d, %d, %d}},\n", size-1, previous[0], previous[1], previous[2], previous[3])
		}
		previous = alignment
	}
	fmt.Fprintf(&b, "{^uint64(0), [4]uint16{%d, %d, %d, %d}},\n", previous[0], previous[1], previous[2], previous[3])
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}
